[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/payara/*.log
    Path_Key          source_file
    Tag               payara.*
    Parser            payara_json
    Refresh_Interval  5

[OUTPUT]
    Name          http
    Match         payara.*
    Host          openobserve
    Port          5080
    URI           /api/default/payara_logs/_json
    Format        json
    http_User     admin@example.com
    http_Passwd   ComplexPassword123!
    tls           off